import Head from "next/head";
import NavBar from "@/components/nav/nav";
import Hero from "@/components/hero/hero";
import ItemParentComp from "@/components/itemComp/itemParentComp";
import { useState } from "react";
import Reason from "@/components/reason/reasonComp";
import NewsLetter from "@/components/newsletter/newsLetterComp";
import first from "../public/assets/kid.png";
import mid from "../public/assets/mid.png";
import last from "../public/assets/last.png";
import Testimony from "@/components/testimony/testimony";
import Numbers from "@/components/numbers/numbers";
import Enroll from "@/components/enroll/enroll";
import Footer from "@/components/footer/footer";
import type { NextPageWithLayout } from "./_app";
const news: { message: string; image: any; link: string }[] = [
  {
    message: " New school fees release ahead of next academic year",
    link: "/",
    image: first,
  },
  {
    message: "New school fees release ahead of next academic year",
    link: "/",
    image: mid,
  },
  {
    message: "New school fees release ahead of next academic year",
    link: "/",
    image: last,
  },
];

const Home: NextPageWithLayout = () => {
  const [menu, setMenu] = useState(false);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`w-full  flex flex-col overflow-x-hidden justify-start  ${
          menu ? "h-screen" : "min-h-screen"
        }`}
      >
        {/* navigation */}
        <NavBar handleMenu={() => setMenu((pre) => !pre)} />
        {/* hero section */}
        <Hero />
        {/* Reasons to enroll */}
        <ItemParentComp
          label="Enroll your ward now"
          link={"/enroll-child"}
          title={" Why your ward should be here"}
          subtitle={
            "  Providing an exceptional educational experience fo success"
          }
        >
          <Reason />
        </ItemParentComp>
        {/* newsletters */}
        <ItemParentComp
          back="bg-[#F4F6F8]"
          label="Read More"
          title={"Latest Newsletter"}
          subtitle={
            "Stay up-to-date with the latest news and events at our school"
          }
        >
          <NewsLetter news={news} />
        </ItemParentComp>
        {/* testimony */}
        <Testimony />
        {/* numbers */}
        <Numbers />
        {/* Enroll */}
        <Enroll />
        {/* footer */}
        <Footer />
      </main>
    </>
  );
};

Home.getLayout = function getLayout(page) {
  return page;
};

export default Home;
